### ISSUE TITLE
makeExtendSchemaPlugin throws error

### ISSUE THREAD

**Issue by stlbucket** [graphile/graphile-engine#283]
i'm trying to recreate the randomXXX example from the docs

https://www.graphile.org/postgraphile/extending/#makeextendschemaplugin

the entity i'm using is 'soro.Company' instead of 'app_public.users'.  other than that, I believe my code is identical.  this must be a problem with my code, but i'm seeing this error:

```
Error: Unexpected 'TypeExtensionDefinition' definition; we were expecting 'ObjectTypeExtension', 'InputObjectTypeExtension', 'ObjectTypeDefinition' or 'InputObjectTypeDefinition', i.e. something like 'extend type Foo { ... }'
    at typeDefs.definitions.forEach.definition (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-utils/node8plus/makeExtendSchemaPlugin.js:47:17)
    at Array.forEach (<anonymous>)
    at builder.hook.build (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-utils/node8plus/makeExtendSchemaPlugin.js:23:28)
    at SchemaBuilder.applyHooks (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-build/node8plus/SchemaBuilder.js:145:20)
    at SchemaBuilder.createBuild (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-build/node8plus/SchemaBuilder.js:177:24)
    at SchemaBuilder.buildSchema (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-build/node8plus/SchemaBuilder.js:189:26)
    at Object.exports.createPostGraphileSchema (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/postgraphile-core/node8plus/index.js:223:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
my code:

```
process.env.DATABASE_URL = 'postgres://blahdyblahblah'

const { postgraphile } = require("postgraphile");
const { makeExtendSchemaPlugin, gql } = require("graphile-utils");
const express = require("express");

const app = new express();

const MyRandomCompanyPlugin = makeExtendSchemaPlugin(build => {
  const { pgSql: sql } = build;
  return {
    typeDefs: gql`
      extend type Query {
        randomCompany: Company
      }
    `,
    resolvers: {
      Query: {
        randomCompany: async (
          _query,
          args,
          context,
          resolveInfo,
          { selectGraphQLResultFromTable }
        ) => {
          const rows = await selectGraphQLResultFromTable(
            sql.fragment`soro.company`,
            (tableAlias, sqlBuilder) => {
              sqlBuilder.orderBy(sql.fragment`random()`);
              sqlBuilder.limit(1);
            }
          );
          return rows[0];
        },
      },
    },
  };
});

app.use(
  postgraphile(process.env.DATABASE_URL, ["soro"], {
    graphiql: true,
    appendPlugins: [MyRandomCompanyPlugin],
  })
);
app.listen(3030);
```

if i leave out the plugin, i can see the Company type just fine on the schema.

**Comment by stlbucket** [comment]
also with this minimal server, if i leave out the appendPlugins line, i get warnings such as:

```
Recoverable error occurred:
  graphile-build:warn Error: Type 'CreateQuotePayload' has already been registered!
  graphile-build:warn     at Object.newWithHooks (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-build/node8plus/makeNewBuild.js:519:17)
  graphile-build:warn     at fieldWithHooks (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-build-pg/node8plus/plugins/makeProcField.js:283:21)
  graphile-build:warn     at fieldWithHooks (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-build/node8plus/makeNewBuild.js:386:29)
  graphile-build:warn     at Object.makeProcField (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-build-pg/node8plus/plugins/makeProcField.js:188:10)
  graphile-build:warn     at introspectionResultsByKind.procedure.filter.filter.filter.reduce (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-build-pg/node8plus/plugins/PgMutationProceduresPlugin.js:42:27)
  graphile-build:warn     at Array.reduce (<anonymous>)
  graphile-build:warn     at PgMutationProceduresPlugin.builder.hook (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-build-pg/node8plus/plugins/PgMutationProceduresPlugin.js:24:167)
  graphile-build:warn     at SchemaBuilder.applyHooks (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-build/node8plus/SchemaBuilder.js:145:20)
  graphile-build:warn     at fields (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-build/node8plus/makeNewBuild.js:405:40)
  graphile-build:warn     at resolveThunk (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphql/type/definition.js:159:40) +0ms
Recoverable error occurred:
  graphile-build:warn Error: Type 'CreateQuoteLineItemPayload' has already been registered!
  graphile-build:warn     at Object.newWithHooks (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-build/node8plus/makeNewBuild.js:519:17)
  graphile-build:warn     at fieldWithHooks (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-build-pg/node8plus/plugins/makeProcField.js:283:21)
  graphile-build:warn     at fieldWithHooks (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-build/node8plus/makeNewBuild.js:386:29)
  graphile-build:warn     at Object.makeProcField (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/graphile-build-pg/node8plus/plugins/makeProcField.js:188:10)
  graphile-build:warn     at introspectionResultsByKind.procedure.filter.fil...
```

i only get five sets of these warning and they don't seem to be causing an issue, but they seem like something that should be tracked down.   should i file a separate issue?

**Comment by benjie** [comment]
Your “has already been registered” errors hint that you’ve got two things that result in the same name; e.g. having a function called “create_quote” and also a table called “quote” with default mutations.

**Comment by benjie** [comment]
The main issue seems to be that different versions of GraphQL use different names for type extensions. What version of GraphQL are you using? Simplest workaround right now might be to up/down-grade.

**Comment by benjie** [comment]
Yeah it seems that the names of these types changed in https://github.com/graphql/graphql-js/pull/1102 and https://github.com/graphql/graphql-js/pull/1117 at the end of last year. Seems you need at least GraphQL v0.12+ to use that part of `graphile-utils`.

**Comment by benjie** [comment]
Tagging this wontfix because I don't think it's worth investing time in supporting a legacy version of graphql. I hope this doesn't cause you any issues.

**Comment by stlbucket** [comment]
disabling default mutations did solve the one issue.

and i did have graphql 9.X

however, i've now blown away my node_modules and reinstalled everything.  i am now on graphql 13.2 and am still seeing errors:

```
Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/postgraphile/node_modules/graphql/jsutils/instanceOf.js:17:13)
    at isSchema (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/postgraphile/node_modules/graphql/type/schema.js:48:35)
    at validateSchema (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/postgraphile/node_modules/graphql/type/validate.js:51:25)
    at assertValidSchema (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/postgraphile/node_modules/graphql/type/validate.js:76:16)
    at Object.validate (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/postgraphile/node_modules/graphql/validation/validate.js:61:35)
    at parseQuery (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:220:48)
    at Promise.all.paramsList.map (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:496:63)
    at Array.map (<anonymous>)
    at requestHandler (/Users/buckfactor/soro/bitbucket/soro/sales/wa-leaf-sync/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:463:52)
    at <anonymous>
```

i've removed explicit install of graphql from package.json as well as a couple of libs i hadn't thought to clean out (lokka and old-school postgraphile - this is an old repo), and added:

```
  "resolutions": {
    "graphql": "^0.13.0"
  },
```

which doesn't seem to help.  any other ideas how i resolve this?   i've verified the graphql version in node_modules is 13.2.

**Comment by stlbucket** [comment]
i am using apollo-client
```
  "peerDependencies": {
    "graphql": "^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0"
  },
```
from graphile-utils/package.json
```
  "dependencies": {
    "debug": ">=2 <3",
    "graphql": ">=0.9 <0.14"
  },
```

how do i find the second graphql lib that is being referenced!?

**Comment by stlbucket** [comment]
may have fixed:

blew everything away.   installed with yarn instead of npm...   not seeing the same error anymore.

**Comment by stlbucket** [comment]
and it works like a charm

**Comment by benjie** [comment]
Awesome 👍  Managing multiple versions of graphql is painful for everyone - it's a common issue.
