### ISSUE TITLE
graphile-build is missing chalk dependency declaration

### ISSUE THREAD

**Issue by leoschweizer** [graphile/graphile-engine#321]
When using the production installation with graphile-build somewhere in the dependency tree, postgrahile does not init properly:
```
Error: Cannot find module 'chalk'
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
     at Module.require (internal/modules/cjs/loader.js:636:17)
     at require (internal/modules/cjs/helpers.js:20:18)
     at Object.<anonymous> (/.../node_modules/graphile-build/node8plus/extend.js:9:14)
```
If I'm not mistaken, graphile-build depends on chalk directly, e.g. here:
https://github.com/graphile/graphile-engine/blob/master/packages/graphile-build/src/extend.js#L2

However, the package.json for grahile-build does not list chalk as a dependency:
https://github.com/graphile/graphile-engine/blob/master/packages/graphile-build/package.json#L32

This does not fail in dev mode, probably because the dev dependency jest includes a dependency on chalk itself.

**Comment by benjie** [comment]
Fixed 👍

**Comment by benjie** [comment]
I'm tracking this issue regarding a patch to depcheck to support monorepos: https://github.com/depcheck/depcheck/issues/245
