### ISSUE TITLE
issue with @graphile-contrib/pg-order-by-related and 4.3.0

### ISSUE THREAD

**Issue by mathroc** [graphile/graphile-engine#383]
the error message:

> TypeError: Cannot read property 'getTableAlias' of undefined,
    at sqlSubselect (/scripts/node_modules/@graphile-contrib/pg-order-by-related/index.js:234:47),
    at orders.forEach (/scripts/node_modules/graphile-build-pg/node8plus/plugins/PgConnectionArgOrderBy.js:117:160),
    at Array.forEach (<anonymous>),
    at orderBy.forEach.item (/scripts/node_modules/graphile-build-pg/node8plus/plugins/PgConnectionArgOrderBy.js:116:22),
    at Array.forEach (<anonymous>),
    at pgQuery (/scripts/node_modules/graphile-build-pg/node8plus/plugins/PgConnectionArgOrderBy.js:113:21),
    at Object.<anonymous> (/scripts/node_modules/graphile-build-pg/node8plus/queryFromResolveDataFactory.js:52:5),
    at queryBuilder.select (/scripts/node_modules/graphile-build-pg/node8plus/plugins/PgBackwardRelationPlugin.js:166:37),
    at callIfNecessary (/scripts/node_modules/graphile-build-pg/node8plus/QueryBuilder.js:28:12),
    at compiledData.(anonymous function).data.(anonymous function).reduce (/scripts/node_modules/graphile-build-pg/node8plus/QueryBuilder.js:449:22),
    at Array.reduce (<anonymous>),
    at QueryBuilder.lock (/scripts/node_modules/graphile-build-pg/node8plus/QueryBuilder.js:444:49),
    at QueryBuilder.lockEverything (/scripts/node_modules/graphile-build-pg/node8plus/QueryBuilder.js:511:10),
    at QueryBuilder.build (/scripts/node_modules/graphile-build-pg/node8plus/QueryBuilder.js:381:10),
    at Object.<anonymous> (/scripts/node_modules/graphile-build-pg/node8plus/queryFromResolveDataFactory.js:349:32),
    at queryBuilder.select (/scripts/node_modules/graphile-build-pg/node8plus/plugins/PgForwardRelationPlugin.js:96:33)

installed versions from yarn.lock:

> mathieu $ rg order-b yarn.lock
25:"@graphile-contrib/pg-order-by-related@^1.0.0-beta.1":
27:  resolved "https://registry.yarnpkg.com/@graphile-contrib/pg-order-by-related/-/pg-order-by-related-1.0.0-beta.4.tgz#1f6d057f48ab3545146691b0c057eb9141e70098"
mathieu $ rg graphile-bui  yarn.lock
1820:graphile-build-pg@^4.3.0:
1822:  resolved "https://registry.yarnpkg.com/graphile-build-pg/-/graphile-build-pg-4.3.0.tgz#be33d7d45e864954cecba547d50682e50839f86d"
1827:    graphile-build "4.3.0"
1835:graphile-build@4.3.0, graphile-build@^4.3.0:
1837:  resolved "https://registry.yarnpkg.com/graphile-build/-/graphile-build-4.3.0.tgz#7992ccf40fbda9463985631e20444ed9a48ee1ed"

I'll post more if I find something

**Comment by mattbretl** [comment]
Confirmed. The `@graphile-contrib/pg-order-by-related` tests fail against 4.3.0. I'm looking into it.

**Comment by benjie** [comment]
No breaking change was intentional (other than the pgInflection stuff which I’ve reverted)

**Comment by benjie** [comment]
Ohhh; I forgot it can take functions already. Weird that this didn’t show up in the tests.

**Comment by benjie** [comment]
Well; that was easy to fix: https://github.com/graphile/graphile-engine/pull/386

👍

**Comment by benjie** [comment]
(Also this now means there is at least one test for this functionality.)
