### ISSUE TITLE
Unhandled promise rejection in pg-pubsub when PostgreSQL server goes down

### ISSUE THREAD

**Issue by benjie** [graphile/graphile-engine#490]
If the PostgreSQL server goes down (e.g. because you're upgrading it) then pg-pubsub seems to cause a unhandled promise rejection warning

```
UnhandledPromiseRejectionWarning: Error: Attempted connection too many times, setupClient failed
    at setupClient (/app/node_modules/@graphile/pg-pubsub/dist/index.js:102:23)
    at setupClient (/app/node_modules/@graphile/pg-pubsub/dist/index.js:111:24)
```

**Comment by benjie** [comment]
https://github.com/graphile/graphile-engine/blob/c3dd9cf061a1d1498e189a69f1a35befe4bc83f5/packages/pg-pubsub/src/index.ts#L147-L159

Needs exponential-backoff logic, and should just keep retrying indefinitely?
