### ISSUE TITLE
Have errors mentioning smart comments link to smart comments docs

### ISSUE THREAD

**Issue by benjie** [graphile/graphile-engine#524]
e.g. in this error:

```
A serious error occurred when building the initial schema. Exiting because `retryOnInitFail` is not set. Error details:

Error: A naming conflict has occurred - two entities have tried to define the same key 'marketingSource'.

  The first entity was:

    Adding field for column "marketing_source" on table "app_public"."owners". You can rename this field with:

      COMMENT ON COLUMN "app_public"."owners"."marketing_source" IS E'@name newNameHere';

  The second entity was:

    Forward relation for constraint "owners__fk_marketing_source" on table "app_public"."owners". To rename this relation with smart comments:

      COMMENT ON CONSTRAINT "owners__fk_marketing_source" ON "app_public"."owners" IS E'@fieldName newNameHere';
    at Object.extend (/app/node_modules/graphile-build/node8plus/extend.js:35:13)
    at /app/node_modules/graphile-build-pg/node8plus/plugins/PgForwardRelationPlugin.js:54:12
    at SchemaBuilder.applyHooks (/app/node_modules/graphile-build/node8plus/SchemaBuilder.js:250:20)
    at fields (/app/node_modules/graphile-build/node8plus/makeNewBuild.js:499:40)
    at resolveThunk (/app/node_modules/graphql/type/definition.js:383:40)
    at defineFieldMap (/app/node_modules/graphql/type/definition.js:567:18)
    at GraphQLObjectType.getFields (/app/node_modules/graphql/type/definition.js:522:27)
    at typeMapReducer (/app/node_modules/graphql/type/schema.js:320:61)
    at typeMapReducer (/app/node_modules/graphql/type/schema.js:330:22)
    at typeMapReducer (/app/node_modules/graphql/type/schema.js:330:22)
```

Also, push the error stack much further down, and label it to make it clear the error comes from the user's schema not from PostGraphile.

**Comment by benjie** [comment]
I'm not going to add a link because that's a bit overwhelming, but I'm going to indicate change `smart comments` to `'Smart Comments'` which should be enough for someone to google `postgraphile smart comments`.
