### ISSUE TITLE
Error on my machine from versions higher than 4.4.5

### ISSUE THREAD

**Issue by techanvil** [graphile/graphile-engine#570]
```
/home/foo/git-public/bar/demo-service/node_modules/graphile-utils/node8plus/makePgSmartTagsPlugin.js:8
    [graphile_build_pg_1.PgEntityKind.CLASS]: "for tables, composite types, views and materialized views",
                                      ^

TypeError: Cannot read property 'CLASS' of undefined
    at Object.<anonymous> (/home/foo/git-public/bar/demo-service/node_modules/graphile-utils/src/makePgSmartTagsPlugin.ts:35:17)    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/home/foo/git-public/bar/demo-service/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1103:10)    at Object.newLoader [as .js] (/home/foo/git-public/bar/demo-service/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/foo/git-public/bar/demo-service/node_modules/graphile-utils/src/index.ts:22:1)
```

Happy to provide more info, thanks for the software! :)

**Comment by benjie** [comment]
Hi @techanvil try updating both postgraphile and graphile-utils. It seems you may be running a newer version of graphile-utils than PostGraphile. If you’ve installed other graphile modules manually you may need to update those too.

**Comment by techanvil** [comment]
Thanks for the tip! I've just run `yarn upgrade` in my sandbox and all is well. :)
