### ISSUE TITLE
Using @primaryKey yields input type naming conflict

### ISSUE THREAD

**Issue by saerdnaer** [graphile/graphile-engine#685]
### Summary

When I use the smart tag `COMMENT ON TABLE conferences IS  E'@primaryKey acronym';` on following table:
```
CREATE TABLE conferences (
    id SERIAL PRIMARY KEY,
    acronym character varying(255) NOT NULL UNIQUE,
    title character varying(255) NOT NULL,
    description text
);
```

grahile-build fails to generate the mutations with following error:

```
  graphile-build:warn Error: A type naming conflict has occurred - two entities have tried to define the same type 'UpdateConferenceByAcronymInput'.
  graphile-build:warn 
  graphile-build:warn   The first entity was:
  graphile-build:warn 
  graphile-build:warn     Adding table update mutation input type for constraint "conferences_acronym_key" on table "public"."conferences". You can rename the table's GraphQL type via a 'Smart Comment':
  graphile-build:warn     
  graphile-build:warn       COMMENT ON TABLE "public"."conferences" IS E'@name newNameHere\n@primaryKey acronym';
  graphile-build:warn 
  graphile-build:warn   The second entity was:
  graphile-build:warn 
  graphile-build:warn     Adding table update mutation input type for constraint "FAKE_public_conferences_@primaryKey" on table "public"."conferences". You can rename the table's GraphQL type via a 'Smart Comment':
  graphile-build:warn     
  graphile-build:warn       COMMENT ON TABLE "public"."conferences" IS E'@name newNameHere\n@primaryKey acronym';
  graphile-build:warn     at Object.addType (./node_modules/graphile-build/node8plus/makeNewBuild.js:253:17)
  graphile-build:warn     at Object.newWithHooks (./node_modules/graphile-build/node8plus/makeNewBuild.js:659:14)
  graphile-build:warn     at uniqueConstraints.forEach.constraint (./node_modules/graphile-build-pg/node8plus/plugins/PgMutationUpdateDeletePlugin.js:308:29)
  graphile-build:warn     at Array.forEach (<anonymous>)
  graphile-build:warn     at introspectionResultsByKind.class.reduce (./node_modules/graphile-build-pg/node8plus/plugins/PgMutationUpdateDeletePlugin.js:292:27)
  graphile-build:warn     at Array.reduce (<anonymous>)
  graphile-build:warn     at extend.reduce (./node_modules/graphile-build-pg/node8plus/plugins/PgMutationUpdateDeletePlugin.js:63:109)
  graphile-build:warn     at Array.reduce (<anonymous>)
  graphile-build:warn     at PgMutationUpdateDeletePlugin.builder.hook (./node_modules/graphile-build-pg/node8plus/plugins/PgMutationUpdateDeletePlugin.js:63:48)
  graphile-build:warn     at SchemaBuilder.applyHooks (./node_modules/graphile-build/node8plus/SchemaBuilder.js:252:20
  graphile-build:warn     at Array.reduce (<anonymous>)
  graphile-build:warn     at PgMutationUpdateDeletePlugin.builder.hook (./node_modules/postgraphile/node_modules/graphile-build-pg/node8plus/plugins/PgMutationUpdateDeletePlugin.js:63:48)
  graphile-build:warn     at SchemaBuilder.applyHooks (./node_modules/postgraphile/node_modules/graphile-build/node8plus/SchemaBuilder.js:252:20) +48s

```

Is this a bug, or can I change the configuration/schema to work around this problem?

### Additional context

```
    "graphile-build": "^4.9.0",
    "graphile-build-pg": "^4.9.2",
    "postgraphile": "^4.9.2",
    "postgraphile-core": "^4.9.2",
```

**Comment by benjie** [comment]
The table already has a primary key; by marking another column as primary key you now have two primary keys, which is not allowed. The `@primaryKey` comment is intended primarily for views which cannot have true primary keys.
